// <auto-generated />
using System;
using MayTheFourth.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MayTheFourth.Infra.Migrations
{
    [DbContext(typeof(MayTheFourthDataContext))]
    [Migration("20240503005638_AddDb")]
    partial class AddDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("FilmeNaveEstelar", b =>
                {
                    b.Property<int>("FilmesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NavesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmesId", "NavesId");

                    b.HasIndex("NavesId");

                    b.ToTable("FilmeNaveEstelar");
                });

            modelBuilder.Entity("FilmePersonagem", b =>
                {
                    b.Property<int>("FilmesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonagensId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmesId", "PersonagensId");

                    b.HasIndex("PersonagensId");

                    b.ToTable("FilmePersonagem");
                });

            modelBuilder.Entity("FilmePlaneta", b =>
                {
                    b.Property<int>("FilmesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanetasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmesId", "PlanetasId");

                    b.HasIndex("PlanetasId");

                    b.ToTable("FilmePlaneta");
                });

            modelBuilder.Entity("FilmeVeiculo", b =>
                {
                    b.Property<int>("FilmesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeiculosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmesId", "VeiculosId");

                    b.HasIndex("VeiculosId");

                    b.ToTable("FilmeVeiculo");
                });

            modelBuilder.Entity("MayTheFourth.Domain.Entities.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Episodio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Produtor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoAbertura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("MayTheFourth.Domain.Entities.NaveEstelar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapacidadeCarga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificacaoHiperdrive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comprimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumiveis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustoEmCreditos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mglt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passageiros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tripulacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VelocidadeMaxima")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NavesEstelares");
                });

            modelBuilder.Entity("MayTheFourth.Domain.Entities.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnoNascimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorCabelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorOlhos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorPele")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanetaId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("MayTheFourth.Domain.Entities.Planeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clima")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diametro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodoOrbital")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodoRotacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Populacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuperficieAquatica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Terreno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planetas");
                });

            modelBuilder.Entity("MayTheFourth.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapacidadeCarga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comprimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumiveis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustoEmCreditos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passageiros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tripulacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VelocidadeMaxima")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("FilmeNaveEstelar", b =>
                {
                    b.HasOne("MayTheFourth.Domain.Entities.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MayTheFourth.Domain.Entities.NaveEstelar", null)
                        .WithMany()
                        .HasForeignKey("NavesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmePersonagem", b =>
                {
                    b.HasOne("MayTheFourth.Domain.Entities.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MayTheFourth.Domain.Entities.Personagem", null)
                        .WithMany()
                        .HasForeignKey("PersonagensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmePlaneta", b =>
                {
                    b.HasOne("MayTheFourth.Domain.Entities.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MayTheFourth.Domain.Entities.Planeta", null)
                        .WithMany()
                        .HasForeignKey("PlanetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmeVeiculo", b =>
                {
                    b.HasOne("MayTheFourth.Domain.Entities.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MayTheFourth.Domain.Entities.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MayTheFourth.Domain.Entities.Personagem", b =>
                {
                    b.HasOne("MayTheFourth.Domain.Entities.Planeta", "Planeta")
                        .WithMany("Personagens")
                        .HasForeignKey("PlanetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planeta");
                });

            modelBuilder.Entity("MayTheFourth.Domain.Entities.Planeta", b =>
                {
                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
